### ISSUE TITLE
Add text color 

### ISSUE THREAD

**Issue by Chandan-6** [psidh/StrikeOps#2]
Add text color to the category section while creating a new missions - page. It's difficult to find which category of missions are available.
![Screenshot 2024-04-17 215323](https://github.com/psidh/Mission/assets/141998868/32395721-9988-44c9-86d5-92ed58afa5b8)
![Screenshot 2024-04-17 215335](https://github.com/psidh/Mission/assets/141998868/35aebfce-605b-4fc2-88cb-706c11af5d45)
![Screenshot 2024-04-17 215432](https://github.com/psidh/Mission/assets/141998868/da0d167c-c121-4191-ad8b-18c0770d7323)

**Comment by psidh** [comment]
Raise a PR by making the changes

**Comment by Chandan-6** [comment]
Roger that
